// // public class App {
// //     public static void main(String[] args) throws Exception {
        
// //         // Excepciones: eventos que interrumpen el flujo normal de la aplicacion.
// //         int numero1 = 10;
// //         int numero2 = 0;
// //         int resultado;
        
// //         Calculadora calculadora = new Calculadora();

// //         try {

// //             resultado = calculadora.dividir(numero1, numero2);
// //             System.out.println(resultado); 

// //         } catch (CalculadoraException e) {
// //             // java.lang.ArithmeticException: / by zero
// //             // at App.main(App.java:11)
// //             e.printStackTrace(); // Nos dice que tipo de error tiene

// //             // Esto si se imprime
// //             System.out.println("Esto va despues de la excepcion");

// //         } finally { // El finally se imprime si sale por el TRY o el CATCH, sirve para agregar un mensaje final
// //             System.out.println("Hemos finalizado el calculo ya sea exitoso o no");
// //         }

    
// //     }
// // }


